name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      merge:
        description: Merge staging into master first? (y/N)
        required: false
        default: "n"

concurrency:
  group: cd-${{ github.ref }}

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    steps:
      - run: |
          git fetch origin staging
          git fetch origin master
          if [ -n $(git diff staging master --exit-code) ]; then
            echo '::set-output name=has_diff::true'
          else
            echo '::set-output name=has_diff::false'
          fi

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: metadata
    if: github.ref == 'refs/heads/master' && github.event.inputs.merge == 'y'
    steps:
      - run: |
          echo ${{ jobs.metadata.outputs.has_diff }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run merge
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ github.token }}

  # The merge commit from above step did not trigger the Publish Image workflow because of
  # https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
  # so we have to call it ourselves.
  publish:
    name: Publish
    needs: merge
    uses: guidojw/amber-ui/.github/workflows/publish-image.yml@feat/github-actions-ci

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish
    if: |
      contains('refs/heads/staging refs/heads/master', github.ref) &&
      ((github.ref == 'refs/heads/master' && github.event.inputs.merge == 'y' && success()) ||
      (github.event.inputs.merge != 'y' && always()))
    steps:
      - run: echo 'deploy'
