name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      merge:
        description: Merge staging into master first? (y/N)
        required: false
        default: "n"

concurrency:
  group: cd-${{ github.ref }}

jobs:
  # Remove this job someday when GitHub adds support for limiting
  # workflow_dispatch triggering to specific branches only.
  branch-check:
    name: Branch Check
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch
        run: |
          if [ '${{ github.ref }}' != 'refs/heads/staging' && '${{ github.ref }}' != 'refs/heads/master' ]; then
            echo 'This workflow can only be run on branches staging and master.'
            exit 1
          fi

  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    needs: branch-check
    outputs:
      has_diff: ${{ steps.check.outputs.has_diff }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check diff
        id: check
        run: |
          git fetch origin master
          git fetch origin staging
          if ! git diff origin/master origin/staging --exit-code; then
            echo '::set-output name=has_diff::true'
          else
            echo '::set-output name=has_diff::false'
          fi

  merge:
    name: Merge
    runs-on: ubuntu-latest
    needs: metadata
    if: github.event.inputs.merge == 'y'
    steps:
      - name: Validate input
        run: |
          if [ '${{ github.ref }}' != 'refs/heads/master' ]; then
            echo 'Can only merge when the workflow target branch is master.'
            exit 1
          fi
          if ! ${{ fromJSON(needs.metadata.outputs.has_diff) }}; then
            echo 'There is no diff so a merge is not necessary, skipping next steps.'
          fi

      - name: Checkout code
        if: fromJSON(needs.metadata.outputs.has_diff)
        uses: actions/checkout@v2

      - name: Run merge
        if: fromJSON(needs.metadata.outputs.has_diff)
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: staging
          target_branch: master
          github_token: ${{ github.token }}

  # The merge commit from above step did not trigger the Publish Image workflow
  # because of https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
  # so we have to call it ourselves.
  publish:
    name: Publish
    needs: [metadata, merge]
    if: fromJSON(needs.metadata.outputs.has_diff)
    uses: guidojw/gh-actions-test/.github/workflows/publish-image.yml@staging
    with:
      ref: refs/heads/master
    secrets:
      checks_token: ${{ secrets.CHECKS_TOKEN }}

  # Above comment holds for Continuous Integration too.
  # TODO: Call Continuous Integration workflow

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [metadata, publish]
    if: |
      contains('refs/heads/staging refs/heads/master', github.ref) &&
      ((github.event.inputs.merge == 'y' && fromJSON(needs.metadata.outputs.has_diff) &&
      github.ref == 'refs/heads/master' && success()) ||
      ((github.event.inputs.merge != 'y' || !fromJSON(needs.metadata.outputs.has_diff)) && always()))
    steps:
      - run: echo 'deploy'

      - name: Test SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: guidojw.nl
          username: github-actions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls /opt/docker

      - name: Test Slack Webhook
        run: |
          curl -sSf \
            -X POST \
            -H 'Content-type: application/json' \
            -d '{"text": "Deploy for amber-ui '${{ github.ref }}' is finished"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
