name: Publish Image

on:
  push:
    branches: [staging, master]
  workflow_call:
    inputs:
      sha:
        required: false
        type: string
  workflow_dispatch:

env:
  REGISTRY_URL: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ID: 152323

jobs:
  metadata:
    name: Metadata
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_metadata.outputs.tag }}
      build_args: ${{ steps.get_metadata.outputs.build_args }}
    steps:
      - name: Get metadata
        id: get_metadata
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ $BRANCH_NAME = 'master' ]; then
            echo '::set-output name=tag::latest'
          else
            echo '::set-output name=tag::'$BRANCH_NAME
          fi
          if [ $BRANCH_NAME = 'staging' ] || [ $BRANCH_NAME = 'master' ]; then
            BUILD_ARGS='BUILD_HASH='$GITHUB_SHA
            if [ $BRANCH_NAME = 'staging' ]; then
              BUILD_ARGS+=$'\nDEPLOY_TARGET=staging'
            fi
            BUILD_ARGS=${BUILD_ARGS//$'\n'/'%0A'}
            echo '::set-output name=build_args::'$BUILD_ARGS
          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          build-args: ${{ needs.metadata.outputs.build_args }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ needs.metadata.outputs.tag }}

  update_check_run:
    name: Update Check Run
    runs-on: ubuntu-latest
    needs: [metadata, publish]
    if: github.event_name == 'workflow_dispatch' && always()
    steps:
      - name: Get conclusion
        id: get_conclusion
        env:
          RESULTS: ${{ join(needs.*.result, ' ') }}
        run: |
          for RESULT in $RESULTS; do
            if [ $RESULT = 'cancelled' ] || [ $RESULT = 'failure' ]; then
              echo '::set-output name=conclusion::'$RESULT
              exit
            fi;
          done
          echo '::set-output name=conclusion::success'

      - name: Update Publish Image Check Run
        uses: guidojw/actions/update-check-run@v1
        with:
          app_id: ${{ env.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          name: Publish Image
          conclusion: ${{ steps.get_conclusion.outputs.conclusion }}
          details_url:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
