name: Publish Image

on:
  push:
    branches: [staging, master]
  workflow_call:
    inputs:
      ref:
        description: The branch, tag or SHA to publish.
        required: false
        type: string
  workflow_dispatch:

env:
  REGISTRY_URL: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
#  metadata:
#    name: Metadata
#    runs-on: ubuntu-latest
#    outputs:
#      ref: ${{ steps.validate.outputs.ref }}
#    steps:
#      - name: Validate inputs
#        id: validate
#        run: |
#          if [ '${{ inputs.ref }}' != '' ]; then
#            echo 'here'
#            echo '::set-output name=ref::${{ inputs.ref }}'
#          else
#            echo '::set-output name=ref::${{ github.ref }}'
#          fi

  publish:
    name: Publish
    runs-on: ubuntu-latest
#    needs: metadata
    outputs:
      sha: ${{ steps.output.outputs.sha }}
    if: contains('refs/heads/staging refs/heads/master', github.ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Output current commit SHA
        id: output
        run: |
          echo '::set-output name=sha::'$(git rev-parse HEAD)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push staging image
        if: github.ref == 'refs/heads/staging'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:staging

      - name: Build and push production image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          cache-from: type=gha,scope=main
          cache-to: type=gha,scope=main
          tags: |
            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest

  update-check:
    name: Update Checks
    runs-on: ubuntu-latest
    needs: publish
    if: always() && (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call')
    steps:
      - name: Update Publish Check
        uses: LouisBrunner/checks-action@v1.2.0
        with:
          sha: ${{ needs.publish.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Publish
          conclusion: ${{ needs.publish.result }}
